- name: leihs-inventory directory
  file:
    path: /var/www/leihs-inventory
    state: directory
    mode: 0755

- name: disabled page HTML
  template:
    src: disabled.html
    dest: /var/www/leihs-inventory/503.html
    mode: 0644

- name: disabled page config
  template:
    src: disabled.conf
    dest: /etc/apache2/leihs/conf.d/leihs_800_leihs_inventory.conf
    mode: 0644

- name: reload reverse-proxy
  service:
    name: apache2
    state: reloaded