- name: Install postgresql
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - sudo
    - libpq-dev
    - postgresql-client
    - postgresql-contrib-10
    - postgresql-10
    - python-psycopg2
  tags: [internet]
