- include: install.yml

- include: monitor.yml

- name: add root postgresql user
  become: yes
  become_user: postgres
  postgresql_user:
    name: root
    role_attr_flags: CREATEDB,SUPERUSER
    password: root
  tags: debug

- postgresql_db:
    name: root
    login_user: root
    owner: root
  name: Create the a database for root
