- include_tasks: apt.yml

- name: Gather the package facts
  package_facts:
    manager: auto

- name: stop postgresql service (to free up the port before upgrading)
  service:
    name: postgresql
    state: stopped
  when: "'postgresql-9.6' in ansible_facts.packages"

- include_tasks: install.yml

- include_tasks: upgrade.yml
  when: "'postgresql-9.6' in ansible_facts.packages"

- name: start pg service
  service:
    name: postgresql
    state: started

- name: make sure pg port is opened
  wait_for:
    port: '{{ database.port }}'

- name: add root postgresql user
  become: yes
  become_user: postgres
  postgresql_user:
    name: root
    role_attr_flags: CREATEDB,SUPERUSER
    password: root
    encrypted: true
  tags: debug

- postgresql_db:
    name: root
    login_user: root
    owner: root
  name: Create the a database for root
