- include_tasks: apt.yml

- include_tasks: install.yml

- shell: dpkg-query -S 'postgresql-9.6'
  ignore_errors: True
  register: has_pg96

- include_tasks: upgrade.yml
  when: has_pg96|succeeded

- name: make sure main pg is running
  service:
    name: postgresql
    state: started

- include_tasks: monitor.yml

- name: add root postgresql user
  become: yes
  become_user: postgres
  postgresql_user:
    name: root
    role_attr_flags: CREATEDB,SUPERUSER
    password: root
    encrypted: true
  tags: debug

- postgresql_db:
    name: root
    login_user: root
    owner: root
  name: Create the a database for root
