- include_tasks: apt.yml


- shell: dpkg-query -S 'postgresql-9.6'
  ignore_errors: True
  register: has_pg96

- name: stop postgresql service (to free up the port before upgrading)
  service:
    name: postgresql
    state: stopped
  ignore_errors: True
  when: has_pg96|succeeded

- include_tasks: install.yml

- include_tasks: upgrade.yml
  when: has_pg96|succeeded

- name: start pg service
  service:
    name: postgresql
    state: started

- include_tasks: monitor.yml

- name: make sure pg port is opened
  wait_for:
    port: '{{ database.port }}'

- name: add root postgresql user
  become: yes
  become_user: postgres
  postgresql_user:
    name: root
    role_attr_flags: CREATEDB,SUPERUSER
    password: root
    encrypted: true
  tags: debug

- postgresql_db:
    name: root
    login_user: root
    owner: root
  name: Create the a database for root
