- include_tasks: apt.yml

- name: Gather the package facts
  package_facts:
    manager: auto

- include_tasks: upgrade_10_to_15.yml
  when: "'postgresql-10' in ansible_facts.packages"

- include_tasks: install.yml

- include_tasks: root_user.yml

