- name: add root postgresql user
  become: yes
  become_user: postgres
  postgresql_user:
    name: root
    port: 5415
    role_attr_flags: CREATEDB,SUPERUSER
    password: root
    encrypted: true
  tags: debug

- postgresql_db:
    name: root
    login_user: root
    port: 5415
    owner: root
  name: Create the a database for root
