- include: jessie.yml
  when: >
    (ansible_distribution == "Debian"
      and ansible_distribution_release == "jessie")

- apt:
    name: openjdk-8-jdk
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]
  when: >
    (ansible_distribution == "Ubuntu"
      and ansible_distribution_release == "xenial")
