- name: restore jar from cache
  delegate_to: '{{ build_host_java }}'
  when: not force_rebuild
  failed_when: false
  register: restore_cache_my_uberjar
  changed_when: restore_cache_my_uberjar.rc == 0
  args:
    executable: /bin/bash
  shell: |
    set -eux
    DEPLOY_DIR='{{playbook_dir}}'
    source "${DEPLOY_DIR}/bin/.caching-helpers.sh"

    cd $DEPLOY_DIR/../my
    restore_from_cache "my-uberjar"

- name: debug jar build caching
  debug:
    var: restore_cache_my_uberjar
  when: debug_build_caching

- name: create jar
  delegate_to: '{{ build_host_java }}'
  when: not restore_cache_my_uberjar.changed
  args:
    executable: /bin/bash
  shell: |
    set -eux

    export LEIN_SNAPSHOTS_IN_RELEASE=Yes

    DEPLOY_DIR='{{playbook_dir}}'
    source "${DEPLOY_DIR}/bin/.caching-helpers.sh"

    cd $DEPLOY_DIR/../my
    $DEPLOY_DIR/bin/lein uberjar
    save_to_cache "my-uberjar" "target"

- file:
    path: '{{leihs_my_dir}}'
    state: directory
    owner: '{{leihs_my_user}}'
    recurse: yes
  name: create empty {{leihs_my_dir}}

- copy:
    src: '{{playbook_dir}}/../my/target/leihs-my.jar'
    dest: '{{leihs_my_dir}}/leihs-my.jar'
    owner: '{{leihs_my_user}}'
  name: copy jar over to server
