- file:
    path: '{{leihs_my_dir}}'
    state: absent
  name: remove existing leihs-my dir

- include_tasks: user.yml
- include_tasks: jar.yml
- include_tasks: log-dir.yml

- file:
    path: '{{leihs_my_dir}}'
    state: directory
    owner: '{{leihs_my_user}}'
    recurse: yes
  name: set permissions for leihs-my dir

- include_tasks: service.yml
