- file:
    path: "{{leihs_my_dir}}"
    state: absent
  name: remove existing leihs-my dir

- include_tasks: user.yml
- include_tasks: build.yml

- file:
    path: "{{leihs_my_dir}}"
    state: directory
    owner: "{{leihs_my_user}}"
    recurse: yes
  name: create empty {{leihs_my_dir}}

- copy:
    src: "{{playbook_dir}}/../my/target/leihs-my.jar"
    dest: "{{leihs_my_dir}}/leihs-my.jar"
    owner: "{{leihs_my_user}}"
  name: copy jar over to server

- include_tasks: log-dir.yml
- include_tasks: tmp-dir.yml

- file:
    path: "{{leihs_my_dir}}"
    state: directory
    owner: "{{leihs_my_user}}"
    recurse: yes
  name: set permissions for leihs-my dir

- include_tasks: service.yml
