# NOTE: instead of 'hosts: localhost' we need to use 'hosts: all' + 'delegate_to: localhost' so it works when using the `--limit $HOST` argument! `gather_facts: no` is also needed because of this, because in this step we dont want to connect to the remote server(s) yet.
- hosts: all
  gather_facts: no
  tasks:
    - name: Build Admin
      delegate_to: localhost
      tags: build_admin
      import_role:
        name: leihs-admin-install
        tasks_from: build.yml

    - name: Build Borrow
      delegate_to: localhost
      tags: build_borrow
      import_role:
        name: leihs-borrow-install
        tasks_from: build.yml

    - name: Build Mail
      delegate_to: localhost
      tags: build_mail
      import_role:
        name: leihs-mail-install
        tasks_from: build.yml

    - name: Build My
      delegate_to: localhost
      tags: build_my
      import_role:
        name: leihs-my-install
        tasks_from: build.yml


    - name: Build Inventory
      tags: build_inventory
      include_role:
        tasks_from: build.yml
        name: deploy

#      delegate_to: localhost
#      tags: build_inventory
#      import_role:
#        name: deploy  # Role is located in the subproject

#      include_role:
#        name: deploy  # Role is located in the subproject

#    - name: Build Inventory
#      delegate_to: localhost
##      include_role:
##        name: ../inventory/deploy/roles/deploy/build.yml
#      import_role:
#        name: leihs-inventory-install
#        tasks_from: build.yml

#      Try#1
#      block:
#        - include_tasks: ../inventory/deploy/roles/deploy/build.yml

#  ttps://ci.zhdk.ch/cider-ci/ui/workspace/trials/e991f8a9-d3dc-470c-8c52-baddfff8d87c/scripts/pre-buildh
#    "reason": "Could not find or access '/tmp/ci_working-dir/e991f8a9-d3dc-470c-8c52-baddfff8d87c/inventory/deploy/roles/deploy/build.yml' on the Ansible Controller."


#      Try#2
#      https://ci:
#        zhdk:
#          ch/cider-ci/ui/workspace/trials/cb1c2fc8-445f-49e5-bc35-f43029aac17e/scripts/pre-build:
#  https://ci.zhdk.ch/cider-ci/ui/workspace/trials/cb1c2fc8-445f-49e5-bc35-f43029aac17e/scripts/pre-build

    - name: Build Procure
      delegate_to: localhost
      tags: build_procure
      import_role:
        name: leihs-procure-install
        tasks_from: build.yml

    - debug:
        msg: "All local builds OK!"
