- hosts: leihs_server

  tasks:

    - shell: |
        #/bin/bash
        set eux
        psql -d {{database.database}} -c "UPDATE settings SET external_base_url = '{{settings_external_base_url}}'"
      when: settings_external_base_url is defined
      name: configure external base url

