- hosts: leihs_server
  gather_facts: False
  pre_tasks:
    - name: cleanup ansible remote tmp dir
      raw: "rm -rf ~/.ansible/tmp"

- import_playbook: stop_play.yml

- hosts: leihs_server
  vars:
    # if restore from an existing dump on the remote is desired:
    # override remote_pgbin_restore_path with a different value
    # than remote_pgbin_restore_path_default and pointing it to an
    # existing file on the remote will skip copy and later removal of the dump
    remote_pgbin_restore_path_default: '/tmp/restore-dump.pgbin'
    remote_pgbin_restore_path: "{{remote_pgbin_restore_path_default}}"

  tasks:
    - name: make sure current PostgreSQL is installed
      include_role:
        name: postgresql

    - name: make sure the DB is set up
      include_role:
        name: leihs-database-install

    - name: copy dump file to remote
      copy:
        src: "{{database_dump_restore_file_path}}"
        dest: '{{remote_pgbin_restore_path_default}}'
      when: remote_pgbin_restore_path == remote_pgbin_restore_path_default

    - name: reset DB
      shell: |
        set -eux
        cd /leihs/database
        export PATH={{leihs_database_ruby_dir}}/bin:/usr/lib/postgresql/{{postgres_version}}/bin:$PATH
        export DISABLE_DATABASE_ENVIRONMENT_CHECK=1
        ruby -S bundle exec rake db:pg:terminate_connections db:drop db:create
      become: yes
      become_user: "{{leihs_database_user}}"

    - name: restore DB
      shell: |
        set -eux
        cd /leihs/database
        export PATH={{leihs_database_ruby_dir}}/bin:/usr/lib/postgresql/{{postgres_version}}/bin:$PATH
        export FILE={{remote_pgbin_restore_path}}
        export DISABLE_DATABASE_ENVIRONMENT_CHECK=1
        ruby -S bundle exec rake db:pg:terminate_connections db:pg:structure_and_data:restore
      become: yes
      become_user: "{{leihs_database_user}}"
      async: 3600
      poll: 10

    - name: vacuum DB
      shell: /usr/lib/postgresql/{{postgres_version}}/bin/psql -d "{{database.database}}" -c "VACUUM ANALYZE;"
      become: yes
      become_user: root

    - file:
        path: /tmp/restore-dump.pgbin
        state: absent
      name: delete dump file on remote
      when: remote_pgbin_restore_path == remote_pgbin_restore_path_default

