# - include: leihs-legacy-archive_play.yml

- hosts: leihs_server

  roles:

  - role: leihs-deploy-install
    tags: [leihs-deploy-install]

  - role: leihs-database-install
    tags: [leihs-database-install]

  - role: leihs-legacy-install
    tags: [leihs-legacy-install]

  - role: leihs-system-install
    tags: [leihs-system-install]

  - role: configure
    tags: [configure]

  - role: reverse-proxy
    tags: [reverse-proxy]
