# - include: leihs-legacy-archive_play.yml

- hosts: leihs_server

  roles:

  - role: leihs-database-install
    tags: [leihs-database-install]

  - role: leihs-legacy-install
    tags: [leihs-legacy-install]

  - role: leihs-system-install
    tags: [leihs-system-install]
