- hosts: leihs_v3_server
  roles:
    - role: fetch-v3-data

- import_playbook: deploy_play.yml

- hosts: leihs_server
  roles:

  - role: defaults
    tags: [always]

  - role: reverse-proxy-maintenance-page
    tags: [reverse-proxy-maintenance-page]

  - role: stop-services
    tags: [stop-services]

  - role: import-v3-into-v4

  - role: start-services

  - role: reverse-proxy-leihs
    tags: [reverse-proxy, reverse-proxy-leihs]
