- hosts: leihs_server

  roles:

  - role: leihs-deploy-install
    tags: [leihs-deploy-install]

  - role: leihs-database-install
    tags: [leihs-database-install]

  - role: leihs-legacy-install
    tags: [leihs-legacy-install]

  - role: leihs-admin-install
    tags: [leihs-admin-install]

  - role: leihs-my-install
    tags: [leihs-my-install]

  - role: leihs-procure-install
    tags: [leihs-procure-install]
