- hosts: leihs_server

  roles:
    - role: defaults
      tags: [always]

    - role: leihs-database-install
      tags: [leihs-database-install]

    - role: leihs-mail-install
      tags: [leihs-mail-install]

    - role: leihs-my-install
      tags: [leihs-my-install]

    - role: ../inventory/deploy/roles/deploy
      tags: [leihs-inventory-install]

    - role: leihs-admin-install
      tags: [leihs-admin-install]

    - role: leihs-borrow-install
      tags: [leihs-borrow-install]

    - role: leihs-legacy-install
      tags: [leihs-legacy-install]

    - role: leihs-procure-install
      tags: [leihs-procure-install]

    - role: webstats
      tags: [webstats]

