- hosts: all
  gather_facts: False
  pre_tasks:
    - name: install system python
      raw: |
        apt -y update
        if [ $(lsb_release -c -s) = 'focal' ]; then
          apt install -y python3 python-is-python3
        else
          apt install -y python
        fi

- hosts: leihs_gateway

  roles:
    - role: os-setup
      tags: [os-setup]

- hosts: [leihs_server]

  roles:
    - role: os-check
      tags: [os-check]

    - role: set_local_tar_cmd
      tags: [always]

    - role: os-setup
      tags: [os-setup]

    - role: openjdk
      tags: [openjdk]

    - role: postgresql
      tags: [postgresql]

    - role: install
      tags: [install]

    - role: ruby-install
      tags: [ruby-install]

    - role: nodejs-install
      tags: [nodejs-install]
      vars:
        debian_repo_version: "12.x" # should be current LTS
