- hosts: leihs_gateway

  roles:

  - role: os-setup
    tags: [os-setup]

- hosts: [leihs_server]

  # TMP: fix ansible openssl fuckup on *target* nodes(!!!)
  pre_tasks:
  - name: upgrade pyopenssl package
    raw: pip install -UI pyopenssl
    when: install_ansible # …but DONT do it in the container test

  roles:

  - role: os-setup
    tags: [os-setup]

  - role: openjdk8
    tags: [openjdk8]

  - role: postgresql
    tags: [postgresql]

  - role: install
    tags: [install]

  - role: ruby-install
    tags: [ruby-install]

  - role: ansible
    tags: [ansible]
