- hosts: all
  gather_facts: False
  pre_tasks:
    - name: install system python
      raw: |
        #!/usr/bin/env bash
        set -euo pipefail
        apt -y update
        apt install -y python3 python-is-python3

- hosts: leihs_gateway

  roles:
    - role: os-setup
      tags: [os-setup]

- hosts: [leihs_server]

  roles:
    - role: os-check
      tags: [os-check]

    - role: os-setup
      tags: [os-setup]

    - role: openjdk
      tags: [openjdk]

    - role: postgresql
      tags: [postgresql]

    - role: install
      tags: [install]

