- hosts: leihs_gateway

  roles:

  - role: os-setup
    tags: [os-setup]

- hosts: [leihs_server]

  roles:

  - role: os-check
    tags: [os-check]

  - role: os-setup
    tags: [os-setup]

  - role: openjdk
    tags: [openjdk]

  - role: postgresql
    tags: [postgresql]

  - role: install
    tags: [install]

  - role: ruby-install
    tags: [ruby-install]
