- hosts: leihs_gateway

  roles:

  - role: os-setup
    tags: [os-setup]

- hosts: [leihs_server]

  roles:

  - role: os-setup
    tags: [os-setup]

  - role: openjdk8
    tags: [openjdk8]

  - role: postgresql
    tags: [postgresql]

  - role: install
    tags: [install]

  - role: ruby-install
    tags: [ruby-install]

  - role: ansible
    tags: [ansible]
