ci_vim_mode: false

server_timezone: Etc/UTC

# reset Debian default and restore Systemd default: prevent system crashes by
# overflowing disks due to excessive logging
journald_forward_to_syslog: 'no'

ntp_setup: no
ntp_server: pool.ntp.org

ssh_keys_present: []
ssh_keys_absent: []


