ci_vim_mode: false

ci_server_timezone: Etc/UTC

# reset Debian default and restore Systemd default: prevent system crashes by
# overflowing disks due to excessive logging
journald_forward_to_syslog: 'no'

ntp_setup: no
ntp_server: pool.ntp.org

apache2_modules:
  - expires
  - headers
  - proxy
  - proxy_http
  - rewrite
  - ssl
  - xsendfile
  - cache
  - cache_disk
  - cache_socache
  - socache_shmcb

ssh_keys_present: []
ssh_keys_absent: []


