- fetch:
    src: /leihs/var/db-backups/latest.pgbin
    dest: "{{database_dump_restore_file_path}}"
    flat: yes
    fail_on_missing: yes
    name: fetch latest.pgbin

- name: ensure the dump is there 
  delegate_to: localhost
  shell: |
    ls -lah "{{database_dump_restore_file_path}}"

