- fetch:
    src: /leihs/var/db-backups/latest.pgbin
    dest: "{{playbook_dir}}/../tmp/{{inventory_hostname}}_{{ansible_date_time.date}}_dump.pgbin"
    flat: yes
    fail_on_missing: yes
    name: fetch latest.pgbin

- name: ensure the dump is there 
  delegate_to: localhost
  shell: |
    ls -lah "{{playbook_dir}}/../tmp/{{inventory_hostname}}_{{ansible_date_time.date}}_dump.pgbin"

