- name: make sure current PostgreSQL is installed
  include_role:
    name: postgresql

- name: make sure the DB is set up
  include_role:
    name: leihs-database-install

- name: copy dump file to remote
  copy:
    src: "{{database_dump_restore_file_path}}"
    dest: '{{remote_pgbin_restore_path_default}}'
  when: remote_pgbin_restore_path == remote_pgbin_restore_path_default

- name: register ruby version
  shell: |
    set -eu
    source ~/.asdf/current/asdf.sh
    cd {{leihs_database_dir}}
    asdf current ruby | awk '{print $2}'
  args:
    chdir: "{{leihs_database_dir}}"
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{leihs_database_user}}"
  become_method: sudo
  register: leihs_database_ruby_version

- set_fact:
    leihs_database_ruby_dir: "/home/{{leihs_database_user}}/.asdf/installs/ruby/{{leihs_database_ruby_version.stdout}}"

- name: Drop DB
  shell: |
    #!/usr/bin/env bash
    set -euo pipefail
    cd /leihs/database
    export PATH={{leihs_database_ruby_dir}}/bin:/usr/lib/postgresql/{{postgres_version}}/bin:$PATH
    export DISABLE_DATABASE_ENVIRONMENT_CHECK=1
    ruby -S bundle exec rake db:pg:terminate_connections db:drop db:create
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{leihs_database_user}}"

- name: Drop DB
  postgresql_db:
    name: "{{database.database}}"
    port: 5415
    state: absent
    login_user: root

- name: Drop create DB
  postgresql_db:
    name: "{{database.database}}"
    port: 5415
    lc_collate: de_CH.UTF-8
    lc_ctype: de_CH.UTF-8
    state: present
    template: template0
    login_user: root

- name: restore DB
  shell: |
    #!/usr/bin/env bash
    set -euo pipefail
    cd /leihs/database
    export PATH={{leihs_database_ruby_dir}}/bin:/usr/lib/postgresql/{{postgres_version}}/bin:$PATH
    export FILE={{remote_pgbin_restore_path}}
    export DISABLE_DATABASE_ENVIRONMENT_CHECK=1
    ruby -S bundle exec rake db:pg:terminate_connections db:pg:structure_and_data:restore
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{leihs_database_user}}"
  async: 3600
  poll: 10

- name: vacuum DB
  shell: /usr/lib/postgresql/{{postgres_version}}/bin/psql --port 5415 -d "{{database.database}}" -c "VACUUM ANALYZE;"
  become: yes
  become_user: root
  async: 3600
  poll: 10

- file:
    path: /tmp/restore-dump.pgbin
    state: absent
  name: delete dump file on remote
  when: remote_pgbin_restore_path == remote_pgbin_restore_path_default

