- file:
    path: '{{leihs_procurement_dir}}'
    state: absent
  name: remove existing leihs-procurement dir

- include_tasks: user.yml

- include_tasks: nodejs.yml
  vars:
    debian_repo_version: '8.x' # curent LTS
    nodejs_nodesource_pin_priority: 500

- include_tasks: jar.yml
- include_tasks: log-dir.yml
- include_tasks: frontend.yml

- file:
    path: '{{leihs_procurement_dir}}'
    state: directory
    owner: '{{leihs_procurement_user}}'
    recurse: yes
  name: set permissions for leihs-procurement dir

- include_tasks: service.yml
