- name: start leihs-admin.service
  service:
    name: leihs-admin.service
    state: started
    enabled: yes

- name: start leihs-my.service
  service:
    name: leihs-my.service
    state: started
    enabled: yes

- name: start leihs-procure.service
  service:
    name: leihs-procure.service
    state: started
    enabled: yes

- name: start leihs-procure-client.service
  service:
    name: leihs-procure-client.service
    state: started
    enabled: yes
 
- name: start leihs-legacy.service
  service:
    name: leihs-legacy.service
    state: started
    enabled: yes

- name: start leihs-legacy-cron.timer
  service:
    name: leihs-legacy-cron.timer
    state: started
    enabled: yes

- name: wait for leihs-admin.service
  wait_for:
    host: localhost
    port: '{{leihs_admin_port}}'
    timeout: 180

- name: wait for leihs-my.service
  wait_for:
    host: localhost
    port: '{{leihs_my_port}}'
    timeout: 180

- name: wait for leihs-procure.service
  wait_for:
    host: localhost
    port: '{{leihs_procure_port}}'
    timeout: 180

- name: wait for leihs-procure-client.service
  wait_for:
    host: localhost
    port: '{{leihs_procure_client_port}}'
    timeout: 180

- name: wait for leihs-legacy.service
  wait_for:
    host: localhost
    port: '{{leihs_legacy_port}}'
    timeout: 180
