- name: start leihs-mail.service
  service:
    name: leihs-mail.service
    state: started
    enabled: yes

- name: start leihs-admin.service
  service:
    name: leihs-admin.service
    state: started
    enabled: yes

- name: start leihs-my.service
  service:
    name: leihs-my.service
    state: started
    enabled: yes

- name: start leihs-borrow.service
  service:
    name: leihs-borrow.service
    state: started
    enabled: yes

- name: start leihs-procure.service
  service:
    name: leihs-procure.service
    state: started
    enabled: yes

- name: start leihs-legacy.service
  service:
    name: leihs-legacy.service
    state: started
    enabled: yes

- name: start leihs-legacy-cron.timer
  service:
    name: leihs-legacy-cron.timer
    state: started
    enabled: yes

- name: wait for leihs-admin.service
  wait_for:
    host: localhost
    port: "{{LEIHS_ADMIN_HTTP_PORT}}"
    timeout: 180

- name: wait for leihs-my.service
  wait_for:
    host: localhost
    port: "{{LEIHS_MY_HTTP_PORT}}"
    timeout: 180

- name: wait for leihs-borrow.service
  wait_for:
    host: localhost
    port: "{{LEIHS_BORROW_HTTP_PORT}}"
    timeout: 180

- name: wait for leihs-procure.service
  wait_for:
    host: localhost
    port: "{{LEIHS_PROCURE_HTTP_PORT}}"
    timeout: 180

- name: wait for leihs-legacy.service
  wait_for:
    host: localhost
    port: "{{LEIHS_LEGACY_HTTP_PORT}}"
    timeout: 180
