- command: which gnutar
  register: localhost_gnutar
  delegate_to: localhost
  failed_when: false

- set_fact:
    local_tar_cmd: 'gnutar'
  when: "localhost_gnutar.rc == 0"
  delegate_to: localhost

- set_fact:
    local_tar_cmd: 'tar'
  when: "localhost_gnutar.rc != 0"
  delegate_to: localhost

