- name: create jar
  delegate_to: '{{ build_host_java }}'
  args:
    executable: /bin/bash
  shell: |
    set -eux
    DEPLOY_DIR='{{playbook_dir}}'
    cd $DEPLOY_DIR/../mail
    $DEPLOY_DIR/bin/boot uberjar

- file:
    path: '{{leihs_mail_dir}}'
    state: directory
    owner: '{{leihs_mail_user}}'
    recurse: yes
  name: create empty {{leihs_mail_dir}}

- copy:
    src: '{{playbook_dir}}/../mail/target/leihs-mail.jar'
    dest: '{{leihs_mail_dir}}/leihs-mail.jar'
    owner: '{{leihs_mail_user}}'
  name: copy jar over to server
