- name: create jar
  tags: [builds_artefact, builds_artefact_with_java]
  delegate_to: localhost
  args:
    executable: /bin/bash
  shell: |
    DEPLOY_DIR='{{playbook_dir}}'
    PROJECT_DIR="${DEPLOY_DIR}/../mail"
    ${PROJECT_DIR}/bin/build

- file:
    path: "{{leihs_mail_dir}}"
    state: directory
    owner: "{{leihs_mail_user}}"
    recurse: yes
  name: create empty {{leihs_mail_dir}}

- copy:
    src: "{{playbook_dir}}/../mail/target/leihs-mail.jar"
    dest: "{{leihs_mail_dir}}/leihs-mail.jar"
    owner: "{{leihs_mail_user}}"
  name: copy jar over to server
