- file:
    path: '{{leihs_mail_dir}}'
    state: absent
  name: remove existing leihs-mail dir

- include_tasks: user.yml
- include_tasks: jar.yml
- include_tasks: log-dir.yml

- file:
    path: '{{leihs_mail_dir}}'
    state: directory
    owner: '{{leihs_mail_user}}'
    recurse: yes
  name: set permissions for leihs-mail dir

- include_tasks: service.yml
