- file:
    path: '{{leihs_mail_dir}}/tmp'
    state: directory
    owner: '{{leihs_mail_user}}'
    recurse: yes
  name: create empty leihs-mail tmp dir

- file:
    path: '{{leihs_mail_dir}}'
    state: directory
    owner: '{{leihs_mail_user}}'
    recurse: yes
  name: set permissions for leihs-mail dir
