- name: Install apache2
  apt:
    pkg:
    - apache2
    - libapache2-mod-xsendfile
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  register: apache2_install
  tags: [internet]

- name: Disable default site
  command: a2dissite 000-default
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf

- name: enable modules
  apache2_module:
    name: "{{item}}"
  with_items: '{{apache2_modules}}'


