- include_tasks: install.yml

- name: clean if enabled
  include_tasks: clean_slate.yml
  when: reverse_proxy_clean_slate

- name: log permissions
  include_tasks: log_permissions.yml

- file:
    path: /etc/apache2/leihs/conf.d
    state: directory
    mode: 0755
