- name: Ensure SSL certificate directory exists
  file:
    path: /etc/ssl/localcerts
    state: directory
    mode: 0755

- name: Generate self-signed SSL certificate
  command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout /etc/ssl/localcerts/leihs-target.key
    -out /etc/ssl/localcerts/leihs-target.crt
    -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost"
  args:
    creates: /etc/ssl/localcerts/leihs-target.crt

- name: disable all leihs sites
  shell: rm -rf /etc/apache2/sites-enabled/leihs*

- name: maintenance page directory
  file:
    path: /etc/apache2/leihs-maintenance
    state: directory
    mode: 0755

- name: maintenance page directory
  file:
    path: /var/www/leihs-maintenance
    state: directory
    mode: 0755

- name: maintenance page HTML
  template:
    src: maintenance-page.html
    dest: /var/www/leihs-maintenance/503.html
    mode: 0644

- include_tasks: virtual-host.yml
  with_indexed_items: "{{leihs_virtual_hosts}}"

- name: restart reverse-proxy
  service:
    name: apache2
    state: restarted
