- shell: |
    set -eux
    export PATH=/home/{{leihs_database_user}}/.rubies/ruby-{{leihs_database_ruby_version}}/bin:$PATH
    export RAILS_ENV=production
    cd /leihs/database/
    bundle exec rake db:drop
    bundle exec rake db:create db:migrate VERSION=100
  name: drop existing database, create new and migrate to 100
  become_user: '{{leihs_database_user}}'
  become_method: sudo

