- include_tasks: database-clean-and-prepare.yml
- include_tasks: setup-import-data.yml

- shell: |
    set -eux
    cd /leihs/legacy
    export PATH=/home/{{leihs_legacy_user}}/.rubies/ruby-{{leihs_legacy_ruby_version}}/bin:$PATH
    export RAILS_ENV=production
    export FILE=/tmp/import-v3/db_data.yml
    export ATTACHMENTS_PATH=/tmp/import-v3/public/attachments/
    export IMAGES_PATH=/tmp/import-v3/public/images/attachments/
    export PROCUREMENT_ATTACHMENTS_PATH=/tmp/import-v3/public/system/procurement/attachments/files/
    export PROCUREMENT_IMAGES_PATH=/tmp/import-v3/public/system/procurement/main_categories/images/
    bundle exec rake leihs:dbio:import
  become_user: '{{leihs_legacy_user}}'
  become_method: sudo
  name: do import

- file:
    path: /tmp/import-v3
    state: absent
  name: clean import data
