- file:
    path: /tmp/import-v3
    state: absent

- file:
    path: /tmp/import-v3
    state: directory

- copy:
    src: tmp/v3/files.tar.gz
    dest: /tmp/import-v3/files.tar.gz
  name: copy db_data.yml

- copy:
    src: tmp/v3/db_data.yml
    dest: /tmp/import-v3/db_data.yml
  name: copy db_data.yml

- shell: |
    set -eux
    cd /tmp/import-v3
    tar xfz files.tar.gz
  name: extract files

- file:
    path: /tmp/import-v3
    state: directory
    owner: leihs-legacy
    name: set owner to leihs-legacy
