- copy:
    src: "{{import_file_path}}"
    dest: /tmp/leihs-import
  when: import_file_path is defined
  name: copy import file

- file:
    path: /tmp/leihs-scripts
    state: directory
  name: created /tmp/leihs-scripts directory

- copy:
    src: "{{role_path}}/shared"
    dest: /tmp/leihs-scripts/shared/
  name: copy shared script files

- copy:
    src: "{{script_file_path}}"
    dest: /tmp/leihs-scripts/script.rb
  name: copy script file

- file:
    path: "{{logfile_path}}"
    state: touch
    owner: "{{leihs_legacy_user}}"
  name: create log file

- shell: |
    #!/bin/bash
    set -eux
    source ~/.asdf/current/asdf.sh

    cd {{leihs_legacy_dir}}

    export RAILS_ENV=production
    export IMPORT_FILE=/tmp/leihs-import
    export LEIHS_SECRET={{leihs_master_secret}}

    bundle install > /dev/null
    bundle exec rails runner /tmp/leihs-scripts/script.rb 

  args:
    executable: /bin/bash
  become: yes
  become_user: "{{leihs_legacy_user}}"
  register: result
  name: run rails script

- debug:
    var: result.stdout_lines
  name: debug result.stdout_lines

- copy:
    content: "{{ result.stdout }}"
    dest: "{{logfile_path}}"
  name: write result.stdout to log file

- fetch:
    src: "{{logfile_path}}"
    dest: "{{playbook_dir}}/tmp/log/{{inventory_hostname}}/{{logfile_name}}"
    fail_on_missing: yes
    flat: yes
  name: fetch log file
