- shell: |
    set -eux
    cd /leihs/database
    export PATH=$HOME/.rubies/ruby-{{leihs_database_ruby_version}}/bin:$PATH
    export RAILS_ENV=production
    export DISABLE_DATABASE_ENVIRONMENT_CHECK=1
    ruby -S bundle exec rake db:environment:set
    ruby -S bundle exec rake db:drop db:create
  become: yes
  become_user: '{{leihs_database_user}}'
  name: create and migrate database

- shell: |
    set -eux
    cd /leihs/legacy
    export PATH=$HOME/.rubies/ruby-{{leihs_legacy_ruby_version}}/bin:$PATH
    export RAILS_ENV=production
    export FILE=features/personas/demo.pgbin
    export LEIHS_SECRET={{leihs_master_secret}}
    ruby -S bundle exec rake db:pg:structure_and_data:restore
  become: yes
  become_user: '{{leihs_legacy_user}}'
  name: seed the database
