- name: create jar
  tags: [builds_artefact, builds_artefact_with_java]
  delegate_to: localhost
  args:
    executable: /bin/bash
  shell: |
    DEPLOY_DIR='{{playbook_dir}}'
    PROJECT_DIR="${DEPLOY_DIR}/../procure"
    ${PROJECT_DIR}/bin/build

- file:
    path: "{{leihs_procure_dir}}"
    state: directory
    owner: "{{leihs_procure_user}}"
    recurse: yes
  name: create empty {{leihs_procure_dir}}

- copy:
    src: "{{playbook_dir}}/../procure/server/target/leihs-procure.jar"
    dest: "{{leihs_procure_dir}}/leihs-procure.jar"
    owner: "{{leihs_procure_user}}"
  name: copy jar over to server
