- file:
    path: '{{leihs_procure_dir}}'
    state: absent
  name: remove existing leihs-procure dir

- include_tasks: user.yml

- name: install nodejs
  include_role:
    name: nodejs-install
  vars:
    debian_repo_version: '8.x' # curent LTS

- include_tasks: jar.yml
- include_tasks: log-dir.yml
- include_tasks: frontend.yml

- file:
    path: '{{leihs_procure_dir}}'
    state: directory
    owner: '{{leihs_procure_user}}'
    recurse: yes
  name: set permissions for leihs-procure dir

- include_tasks: service.yml
