- file:
    path: '{{playbook_dir}}/tmp/legacy.tar.gz'
    state: absent
  delegate_to: localhost
  name: remove possibly exisiting archive

- when: zhdk_agw_info_file_path is defined
  shell: |
    #/bin/bash
    set -eux
    cd '{{playbook_dir}}/../legacy'
    git crypt unlock
  delegate_to: localhost
  name: git uncrypt legacy

- shell: |
    #/bin/bash
    set -eux
    DEPLOY_DIR='{{playbook_dir}}'
    cd $DEPLOY_DIR/../legacy
    $DEPLOY_DIR/bin/git-archive-all -v $DEPLOY_DIR/tmp/legacy.tar.gz
  delegate_to: localhost
  name: create archive

- file:
    path: /leihs/legacy
    state: absent
  name: remove existing /leihs/legacy

- file:
    path: /leihs/legacy
    state: directory
    owner: '{{leihs_legacy_user}}'
    recurse: yes
  name: create empty /leihs/legacy

- file:
    path: /tmp/legacy.tar.gz
    state: absent
  name: remove existing archive

- unarchive:
    src: '{{playbook_dir}}/tmp/legacy.tar.gz'
    dest: /leihs/legacy
    owner: '{{leihs_legacy_user}}'
  name: extract archive


