- name: remove possibly exisiting archive
  delegate_to: localhost
  run_once: true
  file:
    path: "{{playbook_dir}}/tmp/legacy.tar.gz"
    state: absent

- name: create archive
  delegate_to: localhost
  run_once: true
  shell: |
    #!/usr/bin/env bash
    set -euo pipefail
    {{playbook_dir}}/bin/git-archive-all \
      -C "{{playbook_dir}}/../legacy" --prefix='' --force-submodules \
      "{{playbook_dir}}/tmp/legacy.tar.gz"
  args:
    executable: /bin/bash

- file:
    path: /leihs/legacy
    state: absent
  name: remove existing /leihs/legacy

- file:
    path: /leihs/legacy
    state: directory
    owner: "{{leihs_legacy_user}}"
    recurse: yes
  name: create empty /leihs/legacy

- file:
    path: /tmp/legacy.tar.gz
    state: absent
  name: remove existing archive

- unarchive:
    src: "{{playbook_dir}}/tmp/legacy.tar.gz"
    dest: /leihs/legacy
    owner: "{{leihs_legacy_user}}"
  name: extract archive
