- import_tasks: shared/task_install_ruby.yml
  vars:
    become_user: "{{leihs_legacy_user}}"

- shell: |
    set -eux
    export PATH=$HOME/.rubies/ruby-{{leihs_legacy_ruby_version}}/bin:$PATH
    which gem
    gem install bundler
    cd /leihs/legacy
    bundle install --retry=12 --without development --without test
  become: yes
  become_user: "{{leihs_legacy_user}}"
  become_method: sudo
  name: install bundler and bundle
