- file:
    path: "{{playbook_dir}}/tmp/legacy.tar.gz"
    state: absent
  delegate_to: localhost
  name: remove possibly exisiting archive

- shell: |
    cd "{{playbook_dir}}/../legacy"
    {{local_tar_cmd}} -cz --exclude-vcs --exclude-vcs-ignores --exclude "./node_modules" --exclude "./tmp" --exclude "./spec" --exclude "./features" \
      -f "{{playbook_dir}}/tmp/legacy.tar.gz" .
  delegate_to: localhost
  name: create archive

- file:
    path: /leihs/legacy
    state: absent
  name: remove existing /leihs/legacy

- file:
    path: /leihs/legacy
    state: directory
    owner: "{{leihs_legacy_user}}"
    recurse: yes
  name: create empty /leihs/legacy

- file:
    path: /tmp/legacy.tar.gz
    state: absent
  name: remove existing archive

- unarchive:
    src: "{{playbook_dir}}/tmp/legacy.tar.gz"
    dest: /leihs/legacy
    owner: "{{leihs_legacy_user}}"
  name: extract archive
