- file:
    path: '{{playbook_dir}}/tmp/legacy.tar.gz'
    state: absent
  delegate_to: localhost
  name: remove possibly exisiting archive

- command: 'tar -cz -f "{{playbook_dir}}/tmp/legacy.tar.gz" -C "{{playbook_dir}}/../legacy" .'
  delegate_to: localhost
  name: create archive

- file:
    path: /leihs/legacy
    state: absent
  name: remove existing /leihs/legacy

- file:
    path: /leihs/legacy
    state: directory
    owner: '{{leihs_legacy_user}}'
    recurse: yes
  name: create empty /leihs/legacy

- file:
    path: /tmp/legacy.tar.gz
    state: absent
  name: remove existing archive

- unarchive:
    src: '{{playbook_dir}}/tmp/legacy.tar.gz'
    dest: /leihs/legacy
    owner: '{{leihs_legacy_user}}'
  name: extract archive
