- shell: |
    #/bin/bash
    set eux
    ruby-install --no-install-deps --no-reinstall ruby {{leihs_legacy_ruby_version}}
  become: yes
  become_user: leihs-legacy
  become_method: sudo
  name: install ruby

- shell: |
    #/bin/bash
    set eux
    export PATH=$HOME/.rubies/ruby-{{leihs_legacy_ruby_version}}/bin:$PATH
    which gem
    gem install bundler
    cd /leihs/legacy
     bundle install
  become: yes
  become_user: leihs-legacy
  become_method: sudo
  name: install bundler and bundle
