- template:
    src: leihs-legacy.service
    dest: /etc/systemd/system/leihs-legacy.service
    mode: 0644
  name: copy  leihs-legacy.service

- template:
    src: leihs-legacy-cron.service
    dest: /etc/systemd/system/leihs-legacy-cron.service
    mode: 0644
  name: install leihs-legacy-cron.service

- template:
    src: leihs-legacy-cron.timer
    dest: /etc/systemd/system/leihs-legacy-cron.timer
    mode: 0644
  name: install leihs-legacy-cron.timer

- command: systemctl daemon-reload
  changed_when: false
  name: reload systemctl
