- shell: |
    set -eux
    source /etc/profile.d/rbenv-load.sh
    cd {{leihs_v3_root_dir}}
    export RAILS_ENV=production
    export PATH="${HOME}/.rbenv/versions/2.3.1/bin:${PATH}"
    ruby -S bundle exec rake leihs:dbio:export
  args:
    executable: /bin/bash
  when: false
  # become_user: '{{leihs_v3_user}}'
  # become_method: sudo

- fetch:
    src: '{{leihs_v3_root_dir}}/tmp/db_data.yml'
    dest: tmp/db_data.yml
    flat: yes
    fail_on_missing: yes
