- name: install ansible dependencies
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
  - build-essential
  - libffi-dev
  - libssl-dev
  - libyaml-dev
  - python-dev
  - python-pip
  - python2.7
  - python2.7-dev
  - ruby
  tags: [internet]

- name: upgrade pip
  shell: |
    set -eux
    pip install -I --upgrade pip

- name: install ansible via pip
  shell: |
    set -eux
    pip install -I --upgrade ansible=={{leihs_ansible_version}}
