- name: get deploy info
  get_deploy_info_facts: {}
  register: leihs_deploy_info
  delegate_to: localhost
  tags: [internet]

- debug:
    var: leihs_deploy_info.data
  tags: [debug]

- name: write deploy info to file
  template:
    src: deploy-info.yml
    dest: /leihs/config/deploy-info.yml
    mode: 0644
    owner: root
    validate: ruby -e 'require "yaml"; YAML.safe_load(File.read("%s"))'

- name: write releases info to file
  copy:
    src: ../config/releases.yml
    dest: /leihs/config/releases.yml
    mode: 0644
    owner: root
    validate: ruby -e 'require "yaml"; YAML.safe_load(File.read("%s"))'
