- file:
    path: /leihs/config
    state: directory
    recurse: true
    owner: root

- include_tasks: master_secret.yml

- file:
    path: /etc/leihs
    state: directory
    recurse: true
    mode: 0755
    owner: root

- name: resolve leihs version
  shell: |
    if [ -f "{{playbook_dir}}/../LEIHS-VERSION" ]; then
      cat "{{playbook_dir}}/../LEIHS-VERSION"
    else
      git -C "{{playbook_dir}}/.." rev-parse --short HEAD
    fi
  register: leihs_version
  delegate_to: localhost
  run_once: true
  changed_when: false

- name: set env config
  template:
    src: config.env
    dest: /etc/leihs/config.env
    mode: 0600
    owner: root

- include_tasks: database.yml

- command: systemctl daemon-reload
  changed_when: false
  name: reload systemctl
