- file:
    path: /leihs/config
    state: directory
    recurse: true
    owner: root

- include_tasks: master_secret.yml

- include_tasks: deploy_info.yml
  tags: [deploy_info]

- include_tasks: database.yml

- command: systemctl daemon-reload
  changed_when: false
  name: reload systemctl
