- file:
    path: /leihs/config
    state: directory
  name: make sure /leihs/config exists

- template:
    src: master-secret.txt
    dest: /leihs/config/master-secret.txt
    mode: 0600
    owner: root
  when: ( leihs_master_secret is defined ) and ( leihs_master_secret is not none )
  name: safe master-secret.txt

- template:
    src: leihs_create-master-secret.path
    dest: /etc/systemd/system/leihs_create-master-secret.path
    mode: 0644
    owner: root
  name: install leihs_create-master-secret.path

- template:
    src: leihs_create-master-secret.service
    dest: /etc/systemd/system/leihs_create-master-secret.service
    mode: 0644
    owner: root
  name: install leihs_create-master-secret.service

- command: systemctl daemon-reload
  changed_when: false
  name: reload systemctl

- service:
    name: leihs_create-master-secret.service
    enabled: yes
    state: restarted
  name: enable leihs_create-master-secret.service

- service:
    name: leihs_create-master-secret.path
    enabled: yes
    state: started
  name: enable leihs_create-master-secret.path
