- file:
    path: /leihs/config
    state: directory
  name: make sure /leihs/config exists

- file:
    path: "{{item}}"
    state: absent
  name: clean up old {{ item }}
  with_items:
  - /leihs/config/master-secret.txt
  - /etc/systemd/system/leihs_create-master-secret.path
  - /etc/systemd/system/leihs_create-master-secret.service

- command: systemctl daemon-reload
  changed_when: false
  name: reload systemctl
