- service:
    name: leihs-admin.service
    state: stopped
  failed_when: false

- service:
    name: leihs-my.service
    state: stopped
  failed_when: false

- service:
    name: leihs-procure.service
    state: stopped
  failed_when: false

- service:
    name: leihs-procure-client.service
    state: stopped
  failed_when: false

- service:
    name: leihs-legacy.service
    state: stopped
  failed_when: false

- service:
    name: leihs-legacy-cron.timer
    state: stopped
  failed_when: false

- service:
    name: leihs-migration.service
    state: stopped
  failed_when: false
