- service:
    name: leihs-admin.service
    state: stopped
  failed_when: false

- service:
    name: leihs-legacy.service
    state: stopped
  failed_when: false

- service:
    name: leihs-migration.service
    state: stopped
  failed_when: false

