#!/bin/sh -exu

# config
DOCKER_EXTRA_ARGS="${DOCKER_EXTRA_ARGS:-""}"
DOCKER_RUN_EXTRA_ARGS="${DOCKER_RUN_EXTRA_ARGS:-""}"
USE_APPLE_SILICON="${USE_APPLE_SILICON:-}"

if test ! $USE_APPLE_SILICON; then
  DOCKER_EXTRA_ARGS="${DOCKER_EXTRA_ARGS} --platform linux/amd64"
fi

# build the docker image and tag it with a name
docker build ${DOCKER_EXTRA_ARGS} -t leihs/ansible-controller .

# start a temporary container from this image,
# mounting our working directory in it,
# passing through the ENV vars we use directly,
# passing through ssh-agent from host so passwordless auth works,
# then run given command
docker run --rm -it \
    -w "/leihs-build/deploy" \
    -v "$(pwd)/..:/leihs-build" \
    -v "$(pwd)/../tmp:/tmp/tmp" \
    -v "$(pwd)/..:/leihs" \
    -v "/run/host-services/ssh-auth.sock:/ssh-agent" \
    -v "$HOME/.ssh/known_hosts:/root/.ssh/known_hosts" \
    -e SSH_AUTH_SOCK="/ssh-agent" \
    ${DOCKER_EXTRA_ARGS} \
    ${DOCKER_RUN_EXTRA_ARGS} \
    leihs/ansible-controller \
    "$@"
