#!/bin/sh -exu

# build the docker image and tag it with a name
docker build -t leihs/ansible-controller .

# start a temporary container from this image,
# mounting our working directory in it,
# passing through the ENV vars we use directly,
# passing through ssh-agent from host so passwordless auth works,
# then run given command
docker run --rm -it \
    -w "/leihs-build/deploy" \
    -v "$(pwd)/..:/leihs-build" \
    -v "$(pwd)/../tmp:/tmp/tmp" \
    -v "$(pwd)/..:/leihs" \
    -v "/run/host-services/ssh-auth.sock:/ssh-agent" \
    -v "$HOME/.ssh/known_hosts:/root/.ssh/known_hosts" \
    -e SSH_AUTH_SOCK="/ssh-agent" \
    leihs/ansible-controller \
    "$@"
