#!/bin/bash

# S3 server for local development

NAME="leihs-local-build-cache"
DEFAULT_STORE="$(pwd)/tmp/build-cache"

STORE="${LEIHS_BUILD_CACHE_DIR:-$DEFAULT_STORE}"
S3_SERVER_IMG="minio/minio:latest"

mkdir -p "$STORE"

echo "using cache dir: ${STORE}"

docker pull "$S3_SERVER_IMG"

docker run --rm \
    --name "$NAME" \
    -v "${STORE}:/data" \
    -p "9000:9000" \
    -e "MINIO_ACCESS_KEY=${NAME}" \
    -e "MINIO_SECRET_KEY=${NAME}" \
    --user "$(id -u):$(id -g)" \
    "$S3_SERVER_IMG" \
    server /data
