- file:
    path: "{{leihs_borrow_dir}}"
    state: absent
  name: remove existing leihs-borrow dir

- include_tasks: user.yml
- include_tasks: build.yml

- file:
    path: "{{leihs_borrow_dir}}"
    state: directory
    owner: "{{leihs_borrow_user}}"
    recurse: yes
  name: create empty {{leihs_borrow_dir}}

- copy:
    src: "{{playbook_dir}}/../borrow/target/leihs-borrow.jar"
    dest: "{{leihs_borrow_dir}}/leihs-borrow.jar"
    owner: "{{leihs_borrow_user}}"
  name: copy jar over to server

- include_tasks: log-dir.yml
- include_tasks: tmp-dir.yml

- file:
    path: "{{leihs_borrow_dir}}"
    state: directory
    owner: "{{leihs_borrow_user}}"
    recurse: yes
  name: set permissions for leihs-borrow dir

- include_tasks: service.yml
