- file:
    path: "{{leihs_borrow_dir}}"
    state: absent
  name: remove existing leihs-borrow dir

- include_tasks: user.yml
- include_tasks: jar.yml
- include_tasks: log-dir.yml
- include_tasks: tmp-dir.yml

- file:
    path: "{{leihs_borrow_dir}}"
    state: directory
    owner: "{{leihs_borrow_user}}"
    recurse: yes
  name: set permissions for leihs-borrow dir

- include_tasks: service.yml
