- name: build translations.sql file
  delegate_to: localhost
  args:
    executable: /bin/bash
  shell: |
    cd {{playbook_dir}}/../borrow
    ./bin/build-translations

- copy:
    src: "{{playbook_dir}}/../borrow/bin/translations.sql"
    dest: "{{leihs_borrow_dir}}/translations.sql"
    owner: "{{leihs_borrow_user}}"
  name: copy translations.sql file over to server

- name: load translations
  shell: |
    psql -d {{database.database}} < {{leihs_borrow_dir}}/translations.sql
