- file:
    path: '{{playbook_dir}}/tmp/deploy.tar.gz'
    state: absent
  delegate_to: localhost
  name: remove possibly exisiting archive

- file:
    path: /tmp/deploy.tar.gz
    state: absent
  name: remove existing archive

- name: create archive
  shell: |
    #/bin/bash
    set -eux
    DEPLOY_DIR='{{playbook_dir}}'
    cd $DEPLOY_DIR/../deploy
    $DEPLOY_DIR/bin/git-archive-all -v $DEPLOY_DIR/tmp/deploy.tar.gz
  delegate_to: localhost
  args:
    creates: '{{playbook_dir}}/tmp/deploy.tar.gz'

- file:
    path: '{{leihs_deploy_path}}'
    state: absent
  name: remove existing {{leihs_deploy_path}}

- file:
    path: '{{leihs_deploy_path}}'
    state: directory
    owner: root
    recurse: yes
  name: create empty {{leihs_deploy_path}}

- unarchive:
    src: '{{playbook_dir}}/tmp/deploy.tar.gz'
    dest: '{{leihs_deploy_path}}'
    owner: root
  name: extract archive
