- copy:
    content: |
      production: &DEFAULT
        adapter: postgresql
        host: {{database_host}}
        port: {{database_port}}
        pool: 25
        encoding: unicode
        username: {{database_username}}
        password: {{database_password}}
        database: {{database_name}}
      development:
        <<: *DEFAULT
    dest: /leihs/database/config/database.yml
  name: configure legacy database

