- template:
    src: leihs-migration.service
    dest: /etc/systemd/system/leihs-migration.service
    mode: 0644
  name: copy leihs-migration.service

- name: reload systemctl
  systemd:
    daemon_reload: yes
