- file:
    path: "{{playbook_dir}}/tmp/database.tar.gz"
    state: absent
  delegate_to: localhost
  name: remove possibly exisiting archive

- name: create archive
  shell: |
    set -eux
    DEPLOY_DIR='{{playbook_dir}}'
    cd $DEPLOY_DIR/../database
    tar -cz --exclude-vcs --exclude-vcs-ignores --exclude "./spec" \
      -f "{{playbook_dir}}/tmp/database.tar.gz"  .
  delegate_to: localhost

- file:
    path: "{{leihs_database_path}}"
    state: absent
  name: remove existing {{leihs_database_path}}

- file:
    path: "{{leihs_database_path}}"
    state: directory
    owner: "{{leihs_database_user}}"
    recurse: yes
  name: create empty {{leihs_database_path}}

- unarchive:
    src: "{{playbook_dir}}/tmp/database.tar.gz"
    dest: "{{leihs_database_path}}"
    owner: "{{leihs_database_user}}"
  name: extract archive
