- import_tasks: shared/task_install_ruby.yml
  vars:
    become_user: "{{leihs_database_user}}"

- shell: |
    set -eux
    export PATH=$HOME/.rubies/ruby-{{leihs_database_ruby_version}}/bin:$PATH
    gem install bundler
    cd /leihs/database
     bundle install
  become: yes
  become_user: "{{leihs_database_user}}"
  become_method: sudo
  name: install bundler and bundle
