- import_tasks: shared/task_install_ruby.yml
  vars:
    ruby_version: "{{leihs_database_ruby_version}}"
    with_jemalloc: "{{leihs_database_ruby_use_jemalloc}}"
    become_user: "{{leihs_database_user}}"

- name: install bundler and bundle
  shell: |
    set -eux
    unset GEM_ROOT GEM_PATH GEM_HOME
    unset RUBY_VERSION RUBY_ENGINE RUBY_ROOT
    export PATH=$HOME/.rubies/ruby-{{leihs_database_ruby_version}}/bin:$PATH
    gem install bundler:{{leihs_database_ruby_bundler_version}}
    cd /leihs/database
    bundle install --retry=3
  become: yes
  become_user: "{{leihs_database_user}}"
  become_method: sudo
