- include: prepare.yml

- include: journald.yml

- include: time.yml

- include: ntp.yml
  when: ntp_setup
  tags: [ntp]

- include: vim.yml
  when: ci_vim_mode

- include: etckeeper.yml

- include: apache2.yml

- include: monit.yml

- include: vmware.yml

- include: ssh-keys.yml
  tags: [ssh-keys]


