### install and configure monit ###############################################

- name: purge monit
  apt:
    pkg: monit
    state: absent
    update_cache: yes
    cache_valid_time: 3600
    purge: yes
  ignore_errors: true
  tags: [internet]


