- name: dist upgrade
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]

- name: Install general stuff
  apt:
    pkg:
      - build-essential
      - imagemagick
      - nodejs
      - python3-passlib
      - ruby
      - shared-mime-info
      - sudo
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]
