- name: remove maintenance page vhost config
  file:
    path: /etc/apache2/sites-enabled/leihs-maintenance.conf
    state: absent

- name: remove maintenance page directory
  file:
    path: /var/www/leihs-maintenance
    state: absent

- name: disable all leihs sites
  shell: rm -rf /etc/apache2/sites-enabled/leihs*

- name: remove leihs configurations
  file:
    path: /etc/apache2/leihs
    state: absent

- file:
    path: /etc/apache2/leihs/
    state: directory
    mode: 0755

- template:
    src: shared_custom.conf
    dest: /etc/apache2/leihs/shared_custom.conf
    mode: 0644

- template:
    src: shared.conf
    dest: /etc/apache2/leihs/shared.conf
    mode: 0644

- debug:
    var: leihs_virtual_hosts

- include_tasks: virtual-host.yml
  with_indexed_items: "{{leihs_virtual_hosts}}"

- name: restart reverse-proxy
  service:
    name: apache2
    state: restarted
