# NOTE: those vars need to be set. they are listed here for reference but its recommended to define them on the command line,
# example: $ bin/ansible-playbook -i ../zhdk-inventory/test-hosts execute-script_play.yml -e 'script_file=/tmp/myscript.rb'
import_file_path: "{{ import_file }}"
leihs_legacy_dir: /leihs/legacy
leihs_legacy_ruby_dir: "/home/{{leihs_legacy_user}}/.asdf/installs/ruby/{{leihs_legacy_ruby_version.stdout}}"
leihs_legacy_user: leihs-legacy
logfile_name: "leihs-script.{{ansible_date_time.iso8601_basic_short}}.log.txt"
logfile_path: "/tmp/{{logfile_name}}"
script_file_path: "{{ script_file | mandatory }}"
