- name: disable all leihs sites
  shell: rm -rf /etc/apache2/sites-enabled/leihs*

- name: remove leihs configurations
  file:
    path: /etc/apache2/leihs
    state: absent

- name: 'check for presence of letsencrypt cert'
  block:
    - name: 'has_letsencrypt_cert: Set default for variable'
      set_fact: { has_letsencrypt_cert: false }

    - name: 'has_letsencrypt_cert: Get stat for cert file'
      stat: { path: '/etc/letsencrypt/live/{{leihs_external_hostname}}/fullchain.pem' }
      register: cert_file

    - name: 'has_letsencrypt_cert: Get stat for key file'
      stat: { path: '/etc/letsencrypt/live/{{leihs_external_hostname}}/privkey.pem' }
      register: key_file

    - name: 'has_letsencrypt_cert: Set fact to true if certificate and key are present'
      set_fact: { has_letsencrypt_cert: true }
      when: (cert_file.stat.exists is defined and cert_file.stat.exists) and (key_file.stat.exists is defined and key_file.stat.exists)

    - debug: { var: has_letsencrypt_cert }

- name: maintenance page directory
  file:
    path: /var/www/leihs-maintenance
    state: directory
    mode: 0755

- name: maintenance page HTML
  template:
    src: maintenance-page.html
    dest: /var/www/leihs-maintenance/503.html
    mode: 0644

- name: maintenance page vhost config
  template:
    src: maintenance-page-vhost.conf
    dest: /etc/apache2/sites-enabled/leihs-maintenance.conf
    mode: 0644

- name: restart reverse-proxy
  service:
    name: apache2
    state: restarted
