- name: disable all leihs sites
  shell: rm -rf /etc/apache2/sites-enabled/leihs*

- name: remove leihs configurations
  file:
    path: /etc/apache2/leihs
    state: absent

- name: maintenance page directory
  file:
    path: /var/www/leihs-maintenance
    state: directory
    mode: 0755

- name: maintenance page HTML
  template:
    src: maintenance-page.html
    dest: /var/www/leihs-maintenance/503.html
    mode: 0644

- name: maintenance page vhost config
  template:
    src: maintenance-page-vhost.conf
    dest: /etc/apache2/sites-enabled/leihs-maintenance.conf
    mode: 0644

- name: restart reverse-proxy
  service:
    name: apache2
    state: restarted
