- name: maintenance site
  file:
    path: /var/www/leihs-maintenance
    state: directory
    mode: 0755

- template:
    src: 503.html
    dest: /var/www/leihs-maintenance/503.html

- name: disable all leihs sites
  shell: rm /etc/apache2/sites-enabled/leihs_*
  failed_when: false
  register: cmd
  changed_when: cmd.rc != 0

- name: remove leihs configurations
  file:
    path: /etc/apache2/leihs
    state: absent

- name: restart reverse-proxy
  service:
    name: apache2
    state: restarted
