# NOTE: do this first to make sure `leihs-ui` ends up in the build cache. because of the caching it wont take much extra time.
# its also in a separate tasks so its easy to include elsewhere
- name: prepare UI build
  tags: [builds_artefact]
  delegate_to: localhost
  args:
    executable: /bin/bash
  environment:
    USE_DOCKER: "{% if build_with_docker %}YES{% else %}NO{% endif %}"
  shell: |
    DEPLOY_DIR='{{playbook_dir}}'
    PROJECT_DIR="${DEPLOY_DIR}/../admin/leihs-ui"
    ${PROJECT_DIR}/bin/build
