- name: prepare UI build # NOTE: do this first to make sure `leihs-ui` ends up in the build cache. because of the caching it wont take much extra time.
  tags: [builds_artefact]
  delegate_to: localhost
  args:
    executable: /bin/bash
  shell: |
    DEPLOY_DIR='{{playbook_dir}}'
    PROJECT_DIR="${DEPLOY_DIR}/../admin/leihs-ui"
    ${PROJECT_DIR}/bin/build

- name: create jar
  tags: [builds_artefact, builds_artefact_with_java]
  delegate_to: localhost
  args:
    executable: /bin/bash
  shell: |
    DEPLOY_DIR='{{playbook_dir}}'
    PROJECT_DIR="${DEPLOY_DIR}/../admin"
    ${PROJECT_DIR}/bin/build
