- name: create jar
  tags: [builds_artefact, builds_artefact_with_java]
  delegate_to: localhost
  args:
    executable: /bin/bash
  shell: |
    DEPLOY_DIR='{{playbook_dir}}'
    PROJECT_DIR="${DEPLOY_DIR}/../admin"
    ${PROJECT_DIR}/bin/build

- file:
    path: "{{leihs_admin_dir}}"
    state: directory
    owner: "{{leihs_admin_user}}"
    recurse: yes
  name: create empty {{leihs_admin_dir}}

- copy:
    src: "{{playbook_dir}}/../admin/target/leihs-admin.jar"
    dest: "{{leihs_admin_dir}}/leihs-admin.jar"
    owner: "{{leihs_admin_user}}"
  name: copy jar over to server
