- file:
    path: '{{leihs_admin_dir}}'
    state: absent
  name: remove existing /leihs/admin

- include_tasks: user.yml
- include_tasks: jar.yml
- include_tasks: log-dir.yml

- file:
    path: /leihs/admin
    state: directory
    owner: leihs-admin
    recurse: yes
  name: set permissions for /leihs/admin

- include_tasks: service.yml

