- template:
    src: leihs-admin.service
    dest: /etc/systemd/system/leihs-admin.service
    mode: 0644
  name: copy leihs-admin.service
  tags:
    - test

- command: systemctl daemon-reload
  changed_when: false
  name: reload systemctl
  tags:
    - test
