- name: restore leihs-ui from cache
  delegate_to: '{{ build_host_nodejs }}'
  when: not force_rebuild
  failed_when: false
  register: restore_cache_admin_leihs_ui
  changed_when: restore_cache_admin_leihs_ui.rc == 0
  args:
    executable: /bin/bash
  shell: |
    set -eux
    DEPLOY_DIR='{{playbook_dir}}'
    source "${DEPLOY_DIR}/bin/.caching-helpers.sh"

    cd $DEPLOY_DIR/../admin
    restore_from_cache "leihs-ui" "./leihs-ui"

- name: debug leihs-ui build caching
  debug:
    var: restore_cache_admin_leihs_ui
  when: debug_build_caching

- name: create shared-ui
  delegate_to: '{{ build_host_nodejs }}'
  when: not restore_cache_admin_leihs_ui.changed
  args:
    executable: /bin/bash
  shell: |
    set -eux
    DEPLOY_DIR='{{playbook_dir}}'
    source "${DEPLOY_DIR}/bin/.caching-helpers.sh"

    cd "${DEPLOY_DIR}/../admin"
    sh scripts/prepare-shared-ui.sh
    save_to_cache "leihs-ui" "./leihs-ui" "./leihs-ui"

# BUG: https://github.com/ansible/ansible/issues/42090
# - name: make shared-ui tarball
#   delegate_to: '{{ build_host_nodejs }}'
#   archive:
#     path: '{{playbook_dir}}/../admin/leihs-ui'
#     dest: '{{playbook_dir}}/../admin/leihs-ui.tgz'

- name: make shared-ui tarball
  delegate_to: '{{ build_host_nodejs }}'
  command: 'tar -cvz -f "{{playbook_dir}}/../admin/leihs-ui.tgz" .'
  args:
    chdir: '{{playbook_dir}}/../admin/leihs-ui'
    creates: '{{playbook_dir}}/../admin/leihs-ui.tgz'

- name: create empty {{leihs_admin_dir}}/leihs-ui
  file:
    path: '{{leihs_admin_dir}}/leihs-ui'
    state: directory
    owner: '{{leihs_admin_user}}'
    recurse: yes

# - name: copy shared-ui over to server
#   copy:
#     src: '{{playbook_dir}}/../admin/leihs-ui/{{ item }}'
#     dest: '{{leihs_admin_dir}}/leihs-ui/{{ item }}'
#     owner: '{{leihs_admin_user}}'
#   with_items:
#     - 'dist/'
#     - 'bootstrap-theme-leihs/build/'

- name: copy shared-ui over to server
  unarchive:
    src: '{{playbook_dir}}/../admin/leihs-ui.tgz'
    dest: '{{leihs_admin_dir}}/leihs-ui'
    owner: '{{leihs_admin_user}}'
