- name: dist upgrade
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]

- apt:
    pkg:
    - ruby
    - git
    - imagemagick
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags: [internet]

