- name: dist upgrade
  apt: upgrade=dist update_cache=yes cache_valid_time=3600
  tags: [internet]

- apt:
    name: '{{item}}'
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - ruby
    - git
    - imagemagick
  tags: [internet]

